networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: { }
  grafana_storage: { }


services:
  api:
    build:
      context: .
      target: builder
    container_name: sanoptes
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    #expose:
    #  - 9090
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-enterprise:11.5.2
    container_name: grafana
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'